// Isolated UI fixtures: intercept every API request; never write real records.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  await context.addInitScript(() => {
    sessionStorage.setItem('boten_user_token', 'isolated-ui-fixture');
    localStorage.setItem('boten-language', 'zh');
  });
  const user = { id: 'fixture-user', display_name: '验收客户', gender: 'other', birth_date: '1990-01-01', signature: '保留历史', email: 'test@example.com', phone: '13800000000', phone_country: 'CN', address: '原地址', version: 1 };
  let hidden = false;
  const share = { id: 'fixture-share', title: '测试分享', code: '123456', active: true, status: 'active', customer_version: 1, item_count: 1, expires_at: '2099-01-01', created_at: '2026-09-11' };
  let lastPatch;
  const requests = [];
  await context.route('**/api/v1/**', async route => {
    const url = new URL(route.request().url());
    const p = url.pathname;
    const method = route.request().method();
    requests.push([method, p]);
    let data = {};
    if (p.endsWith('/auth/profile/details')) {
      lastPatch = route.request().postDataJSON(); Object.assign(user, lastPatch, { version: user.version + 1 }); data = user;
    } else if (p.endsWith('/auth/profile')) data = user;
    else if (p.endsWith('/auth/countries')) data = { items: [{ code: 'CN', name: '中国', calling_code: '+86' }] };
    else if (p.endsWith('/visibility')) { hidden = route.request().postDataJSON().hidden; data = { hidden }; }
    else if (p.endsWith('/customer/me/shares')) data = { items: (url.searchParams.get('hidden') === 'true') === hidden ? [{ ...share, hidden }] : [], total: (url.searchParams.get('hidden') === 'true') === hidden ? 1 : 0, page: 1 };
    else if (p.endsWith('/staff/customers')) data = { items: [user] };
    else if (p.endsWith('/health')) data = { status: 'ok' };
    else data = { items: [], products: [], options: [], total: 0, unread_count: 0, page: 1 };
    await route.fulfill({ json: data });
  });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const out = path.resolve('tmp/ui-acceptance'); fs.mkdirSync(out, { recursive: true });
  await page.goto('http://127.0.0.1:8081/account/#account-contact');
  await page.locator('#profile-address-submit').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#profile-signature').count(), 0);
  await page.locator('#profile-address').fill('独立联系地址 108 号');
  await page.locator('#profile-address-submit').click();
  await page.locator('#profile-address-status.is-success').waitFor();
  await page.evaluate(() => document.fonts.ready);
  assert.deepEqual(Object.keys(lastPatch).sort(), ['address', 'version']);
  assert.equal(user.signature, '保留历史');
  await page.screenshot({ path: path.join(out, 'profile-desktop.png') });
  await page.locator('[data-account-panel="my-shares"]').click();
  await page.locator('.profile-record-more summary').click();
  await page.locator('[data-personal-operation="hide"]').click();
  await page.locator('[data-personal-confirm]').click();
  await page.locator('#profile-shares-list .profile-list-empty').waitFor();
  await page.locator('#profile-shares-filters [name=hidden]').selectOption('true');
  await page.locator('#profile-shares-filters button').click();
  await page.locator('[data-personal-operation="restore"]').click();
  await page.locator('#profile-shares-list .profile-list-empty').waitFor();
  assert.equal(hidden, false);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-account-panel="account-contact"]').click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(out, 'profile-mobile.png') });
  await page.goto('http://127.0.0.1:8081/admin/');
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.evaluate(() => openQuoteEditor({ title: '隔离验收报价', items: [{ kind: 'product', code: 'CR1016', name: '设备', quantity: 1, price: 100 }], customerName: '原客户', customerEmail: 'original@example.com', customerPhone: '原电话', customerAddress: '原地址', recipientUserId: 'original-id' }));
  const quote = page.locator('.quote-editor-dialog');
  await quote.locator('.quote-customer-search').click();
  assert.ok((await quote.locator('.quote-customer-search').boundingBox()).width >= 96);
  const picker = page.locator('.quote-customer-picker');
  await picker.locator('.quote-customer-result').click();
  assert.equal(await picker.locator('[name=manual_address]').inputValue(), user.address);
  assert.equal(await quote.locator('[name=customer_name]').inputValue(), '原客户');
  await picker.locator('[name=manual_address]').fill('本次报价地址');
  await picker.locator('footer button[value=cancel]').click();
  assert.equal(await quote.locator('[name=customer_address]').inputValue(), '原地址');
  await quote.locator('.quote-customer-search').click();
  await picker.locator('.quote-customer-result').click();
  await picker.locator('[name=manual_address]').fill('本次报价地址');
  await page.screenshot({ path: path.join(out, 'customer-desktop.png') });
  await picker.locator('button[value=apply]').click();
  assert.equal(await quote.locator('[name=customer_address]').inputValue(), '本次报价地址');
  assert.equal(await quote.locator('[name=recipient_user_id]').inputValue(), user.id);
  assert.equal(user.address, '独立联系地址 108 号');
  await page.screenshot({ path: path.join(out, 'quote-desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await quote.locator('.quote-customer-search').click();
  await picker.locator('[data-manual-customer]').click();
  await page.screenshot({ path: path.join(out, 'customer-mobile.png') });
  await picker.locator('button[value=apply]').click();
  assert.equal(await quote.locator('[name=recipient_user_id]').inputValue(), '');
  assert.equal(await quote.locator('button[value=saveAndDeliver]').isDisabled(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  assert.equal(requests.some(([method, p]) => method !== 'GET' && p.includes('/staff/quotes')), false);
  console.log('Personal and quote UI fixtures passed; no real API writes. Screenshots:', out);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
